# -------------------
# Settings
# -------------------

model: 'CVAE'
robot: 'Planar'
dof: 25
len_links: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0]
results_dir: 'results/'

# -------------------
# Network parameters
# -------------------

input_dim: 25 # If vector-based representation: input_dim = 2*dof else input_dim = dof
condition_dim: 2 # (x, y) coordinates of end-effector
latent_dim: 23 # normally: input_dim - condition_dim
num_layers: 10 # number of hidden layers for each, encoder and decoder
hidden_dim: 410 # number of neurons per fully connected layer

# -------------------
# Training
# -------------------

num_epochs: 300
batch_size: 1000
lr_rate: 0.005
weight_decay: 0.0001
variational_beta: 0.0067 # for weighting KLdivergence / reconstruction loss
checkpoint_epoch: 3000

# lr-scheduler
milestones: [100, 200]
gamma: 0.1