# Settings
name: 'INN'
dof: '2DOF'
weight_dir : 'weights/ROBOTSIM_INN_2DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 4 # considers padding, as well
input_dim: 4 # = 2 * number of revolute joints + number of prismatic joints
hidden_dim: 100 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 2 # z

num_layers_subnet: 3
num_coupling_layers: 4

# Training
num_epochs: 60
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.001
checkpoint_epoch: 15

# loss weights
weight_Ly: 0.01
weight_Lz: 100.0
weight_Lx: 100.0
weight_Lxy: 0.1

# lr-scheduler
milestones: [40]
gamma: 0.1