# TRAINABLE PARAMETERS:  67973

# Settings
name: 'CVAE'
dof: '3DOF'
weight_dir : 'weights/ROBOTSIM_CVAE_3DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
input_dim: 3 # 2*3 = 2 * number of joints
hidden_dim: 128 # number of neurons per fully connected layer
latent_dim: 1
condition_dim: 2 # (x, y) coordinates of end-effector

# Training
num_epochs: 90
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.0001
# variational_beta: 0.01 # for weighting KLdivergence/reconstruction loss
variational_beta: 0.001
checkpoint_epoch: 30

# lr-scheduler
milestones: [60, 80]
gamma: 0.1

# Testing
num_samples_config: 50
num_samples_latent: 20