# Settings
weight_dir : 'weights/ROBOTSIM_CVAE_2DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
input_dim: 4 # 2*3 = 2 * number of joints
hidden_dim: 100 # number of neurons per fully connected layer
latent_dim: 2
condition_dim: 2 # (x, y) coordinates of end-effector
use_gpu: False

# Training
num_epochs: 40
batch_size: 250
lr_rate: 0.001
weight_decay: 0.0001
variational_beta: 0.25 # for weighting KLdivergence/reconstruction loss
checkpoint_epoch: 10

# lr-scheduler
step_size: 20
gamma: 0.01

# Testing
num_samples_config: 200
num_samples_latent: 1000