# Settings
model: 'INN'
robot: 'Planar'
dof: 4
len_links: [0.5, 0.5, 0.5, 1]
weight_dir : 'weights/ROBOTSIM_INN_4DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 8 # considers padding, as well
input_dim: 8 # = 2 * number of revolute joints
hidden_dim: 132 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 6 # z

num_layers_subnet: 3
num_coupling_layers: 5

# Training
num_epochs: 80
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.001
checkpoint_epoch: 30

# loss weights
weight_Ly: 0.01
weight_Lz: 100.0
weight_Lx: 100.0
weight_Lxy: 0.1

# lr-scheduler
milestones: [60] # [200] # [70]
gamma: 0.1