# number of trainable parameters: 417864

# Settings
name: 'INN'
dof: '3DOF'
weight_dir : 'weights/robotsim_INN_3dof_v1'
checkpoint_dir: 'checkpoints/robotsim_INN_3dof_v1'

PREPROCESS: 'None'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 3 # considers padding, as well
input_dim: 3 # = 2 * number of revolute joints + number of prismatic joints
# hidden_dim: 128 # number of neurons per fully connected layer
hidden_dim: 100 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 1 # z
# use_gpu: False

# Training
num_epochs: 600
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.0001
checkpoint_epoch: 10000

# loss weights
weight_Ly: 1.0
weight_Lz: 10.0
weight_Lx: 10.0
# weight_Lx: 10.0
weight_Lxy: 10.0

# lr-scheduler
step_size: 200
gamma: 0.1

# Testing
num_samples_config: 1000
num_samples_latent: 2000
