# TRAINABLE PARAMETERS:  340510
# TRAINABLE PARAMETERS:  210030
# TRAINABLE PARAMETERS:  88350

# Settings
name: 'INN'
dof: '3DOF'
weight_dir : 'weights/ROBOTSIM_INN_3DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 6 # considers padding, as well
input_dim: 6 # = 2 * number of revolute joints + number of prismatic joints
hidden_dim: 128 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 4 # z

# Training
num_epochs: 120
batch_size: 500
lr_rate: 0.001
weight_decay: 0.0001
checkpoint_epoch: 30

# loss weights
weight_Ly: 1.0
weight_Lz: 10.0
weight_Lx: 10.0
weight_Lxy: 10.0

# lr-scheduler
milestones: [40, 80, 100]
gamma: 0.1