# -------------------
# Settings
# -------------------

model: 'INN'
robot: 'Planar'
dof: 15
len_links: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0]
results_dir: 'results/'

# -------------------
# Network parameters
# -------------------

input_dim: 15 # If vector-based representation: input_dim = 2*dof else input_dim = dof
total_dim: 15 # for now: total_dim = input_dim
output_dim: 2 # (x, y) coordinates of end-effector
latent_dim: 13 # input_dim - output_dim

num_layers_subnet: 6 # 4 # 5
num_coupling_layers: 8 # 6
hidden_dim: 150 # 100 # 200 # number of neurons per fully connected layer

y_noise_scale : 0.001
zeros_noise_scale : 0.005

# -------------------
# Training
# -------------------

dataset_samples: 1000000
num_epochs: 60
batch_size: 1000
lr_rate: 0.00127 # 0.000177905 # 0.003
weight_decay: 0.00032 # 4.78448e-05 # 0.0001
checkpoint_epoch: 50

# loss weights
weight_Ly: 0.01
weight_Lz: 100.0
weight_Lx: 100.0
weight_Lxy: 0.1

# lr-scheduler
# milestones: [20, 100, 150, 200, 250]
# gamma: 0.5