# Settings
model: 'CVAE'
robot: 'Planar'
dof: 2
len_links: [0.5, 1]
weight_dir : 'weights/ROBOTSIM_CVAE_2DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
input_dim: 4 # 2*2 = 2 * number of joints
hidden_dim: 200 # number of neurons per fully connected layer
latent_dim: 2
condition_dim: 2 # (x, y) coordinates of end-effector
num_layers: 3 # number of hidden layers for each, encoder and decoder

# Training
num_epochs: 60
batch_size: 1000
lr_rate: 0.01
weight_decay: 0.0001
variational_beta: 0.0067 # for weighting KLdivergence/reconstruction loss
checkpoint_epoch: 15

# lr-scheduler
milestones: [20, 40, 50]
gamma: 0.1