# TRAINABLE PARAMETERS:  340510
# TRAINABLE PARAMETERS:  210030
# TRAINABLE PARAMETERS:  88350

# Settings
name: 'INN'
dof: '3DOF'
weight_dir : 'weights/ROBOTSIM_INN_3DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 6 # considers padding, as well
input_dim: 6 # = 2 * number of revolute joints + number of prismatic joints
hidden_dim: 128 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 4 # z

# Training
num_epochs: 150
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.001
checkpoint_epoch: 50

# loss weights
weight_Ly: 0.01
weight_Lz: 100.0
weight_Lx: 100.0
weight_Lxy: 0.1

# lr-scheduler
milestones: [80, 130]
gamma: 0.1