# Settings
name: 'CVAE'
dof: '2DOF'
weight_dir : 'weights/ROBOTSIM_CVAE_2DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
input_dim: 2 # 2*2 = 2 * number of joints
hidden_dim: 100 # number of neurons per fully connected layer
latent_dim: 1
condition_dim: 2 # (x, y) coordinates of end-effector
num_layers: 3 # number of hidden layers for each, encoder and decoder

# Training
num_epochs: 90
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.0001
variational_beta: 0.067 # for weighting KLdivergence/reconstruction loss
checkpoint_epoch: 30

# lr-scheduler
milestones: [20, 60]
gamma: 0.1

# Testing
num_samples_config: 50
num_samples_latent: 2000