# -------------------
# Settings
# -------------------

model: 'CVAE'
robot: 'Planar'
dof: 10
len_links: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0]
results_dir: 'results/'

# -------------------
# Network parameters
# -------------------

input_dim: 10 # If vector-based representation: input_dim = 2*dof else input_dim = dof
condition_dim: 2 # (x, y) coordinates of end-effector
latent_dim: 8 # normally: input_dim - condition_dim
num_layers: 5 # 7 # number of hidden layers for each, encoder and decoder
hidden_dim: 400 # 390 # number of neurons per fully connected layer

# -------------------
# Training
# -------------------

dataset_samples: 1000000
num_epochs: 60
batch_size: 1000
lr_rate: 0.0006394791468367589 # 0.01
weight_decay: 0.00029788928921584617 # 0.0001
variational_beta: 0.0067 # for weighting KLdivergence / reconstruction loss
checkpoint_epoch: 50

# lr-scheduler
milestones: [100, 250]
gamma: 0.1