# Settings
dof: '3DOF'
weight_dir : 'weights/ROBOTSIM_INN_3DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 1e-1
zeros_noise_scale : 5e-2
total_dim: 6 # considers padding, as well
input_dim: 6 # = 2 * number of revolute joints + number of prismatic joints
hidden_dim: 100 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 4 # z
use_gpu: False

# Training
num_epochs: 40
batch_size: 250
lr_rate: 0.001
weight_decay: 0.00001
checkpoint_epoch: 10

# loss weights
weight_Ly: 10.0
weight_Lz: 10.0
weight_Lx: 500.0
weight_Lxy: 200.0

# lr-scheduler
step_size: 10
gamma: 0.1

# Testing
num_samples_config: 500
num_samples_latent: 2000