# Settings
weight_dir : 'weights/ROBOTSIM_CVAE_SIN_COS'
checkpoint_dir: 'checkpoints/'

# Network parameters
input_dim: 6 # 2*3 = 2 * number of joints
hidden_dim: 50 # number of neurons per fully connected layer
latent_dim: 2
condition_dim: 2 # (x, y) coordinates of end-effector
use_gpu: False

# Training
num_epochs: 40
batch_size: 250
lr_rate: 0.001
weight_decay: 0.0001
variational_beta: 0.25 # for weighting KLdivergence/reconstruction loss
checkpoint_epoch: 10

# lr-scheduler
step_size: 15
gamma: 0.1

# Testing
num_samples: 5000