# Settings
name: 'INN'
dof: '2DOF'
weight_dir : 'weights/ROBOTSIM_INN_2DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 4 # considers padding, as well
input_dim: 4 # = 2 * number of revolute joints + number of prismatic joints
hidden_dim: 128 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 2 # z
use_gpu: False

# Training
num_epochs: 60
batch_size: 100
lr_rate: 0.001
weight_decay: 0.0001
checkpoint_epoch: 10

# loss weights
weight_Ly: 10.0
weight_Lz: 1.0
weight_Lx: 1.0
weight_Lxy: 200.0

# lr-scheduler
step_size: 20
gamma: 0.1