# Settings
name: 'INN'
dof: '4DOF'
weight_dir : 'weights/ROBOTSIM_INN_4DOF'
checkpoint_dir: 'checkpoints/'

# Network parameters
y_noise_scale : 0.001
zeros_noise_scale : 0.005
total_dim: 8 # considers padding, as well
input_dim: 8 # = 2 * number of revolute joints
hidden_dim: 128 # number of neurons per fully connected layer
output_dim: 2 # tcp
latent_dim: 6 # z

# Training
num_epochs: 40
batch_size: 1000
lr_rate: 0.001
weight_decay: 0.001
checkpoint_epoch: 100

# loss weights
weight_Ly: 0.01
weight_Lz: 100.0
weight_Lx: 100.0
weight_Lxy: 0.1

# lr-scheduler
milestones: [25, 32]
gamma: 0.1